name: Autograding Tests
"on":
  - push
  - workflow_dispatch

jobs:
  file-stucrture:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: file-stucrture
        run: sudo bash TreeTest.sh
